events { worker_connections 1024; }

http {
    server {
        # Dış dünyadan 1881 ile gelecekler
        listen 1881;

        # 1. API İstekleri (STM32'den gelen veriler)
        location /api/ {
            proxy_pass http://localhost:8000; # İçeride Backend'e git
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. WebSocket İstekleri (Canlı İbreler için)
        location /ws/ {
            proxy_pass http://localhost:8000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        # 3. Frontend (Web Sitesi Arayüzü)
        location / {
            proxy_pass http://localhost:5173; # İçeride Vite'e git
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}